[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# 러스트에서는 패키지를 크레이트(crates)라고 부른다. 크렐이트는 crates.io 사이트에서 가져올 수 있다.
[dependencies]
rand = "0.8.5"